const newsData = [
	{
		title: "You need to know what right-half-plane zeros are",
		website: "(jbconsulting.substack.com)",
		points: "138",
		name: "jbay808",
		time: "4 hours ago",
		comment: "45",
	},
	{
		title:
			"uBlacklist – Block specific sites from appearing in Google search results",
		website: "(github.com/iorate)",
		points: "26",
		name: "sanketpatrikar",
		time: "24 minutes ago",
		comment: "45",
	},
	{
		title: "You need to know what right-half-plane zeros are",
		website: "jbconsulting.substack.com",
		points: "138",
		name: "jbay808",
		time: "4 hours ago",
		comment: "45",
	},
	{
		title: "You need to know what right-half-plane zeros are",
		website: "jbconsulting.substack.com",
		points: "138",
		name: "jbay808",
		time: "4 hours ago",
		comment: "45",
	},
	{
		title: "You need to know what right-half-plane zeros are",
		website: "(jbconsulting.substack.com)",
		points: "138",
		name: "jbay808",
		time: "4 hours ago",
		comment: "45",
	},
	{
		title:
			"uBlacklist – Block specific sites from appearing in Google search results",
		website: "(github.com/iorate)",
		points: "26",
		name: "sanketpatrikar",
		time: "24 minutes ago",
		comment: "45",
	},
	{
		title: "You need to know what right-half-plane zeros are",
		website: "jbconsulting.substack.com",
		points: "138",
		name: "jbay808",
		time: "4 hours ago",
		comment: "45",
	},
	{
		title: "You need to know what right-half-plane zeros are",
		website: "jbconsulting.substack.com",
		points: "138",
		name: "jbay808",
		time: "4 hours ago",
		comment: "45",
	},
	{
		title: "You need to know what right-half-plane zeros are",
		website: "(jbconsulting.substack.com)",
		points: "138",
		name: "jbay808",
		time: "4 hours ago",
		comment: "45",
	},
	{
		title:
			"uBlacklist – Block specific sites from appearing in Google search results",
		website: "(github.com/iorate)",
		points: "26",
		name: "sanketpatrikar",
		time: "24 minutes ago",
		comment: "45",
	},
	{
		title: "You need to know what right-half-plane zeros are",
		website: "jbconsulting.substack.com",
		points: "138",
		name: "jbay808",
		time: "4 hours ago",
		comment: "45",
	},
	{
		title: "You need to know what right-half-plane zeros are",
		website: "jbconsulting.substack.com",
		points: "138",
		name: "jbay808",
		time: "4 hours ago",
		comment: "45",
	},
	{
		title: "You need to know what right-half-plane zeros are",
		website: "(jbconsulting.substack.com)",
		points: "138",
		name: "jbay808",
		time: "4 hours ago",
		comment: "45",
	},
	{
		title:
			"uBlacklist – Block specific sites from appearing in Google search results",
		website: "(github.com/iorate)",
		points: "26",
		name: "sanketpatrikar",
		time: "24 minutes ago",
		comment: "45",
	},
	{
		title: "You need to know what right-half-plane zeros are",
		website: "jbconsulting.substack.com",
		points: "138",
		name: "jbay808",
		time: "4 hours ago",
		comment: "45",
	},
	{
		title: "You need to know what right-half-plane zeros are",
		website: "jbconsulting.substack.com",
		points: "138",
		name: "jbay808",
		time: "4 hours ago",
		comment: "45",
	},
];
export default newsData;
