const newsData = [
	{
		title: "You need to know what right-half-plane zeros are 1",
		website: "(jbconsulting.substack.com)",
		points: "138",
		name: "jbay808",
		time: "4 hours ago",
		comment: "45",
	},
	{
		title:
			"uBlacklist – Block specific sites from appearing in Google search results 2",
		website: "(github.com/iorate)",
		points: "26",
		name: "sanketpatrikar",
		time: "24 minutes ago",
		comment: "45",
	},
	{
		title: "You need to know what right-half-plane zeros are 3",
		website: "jbconsulting.substack.com",
		points: "138",
		name: "jbay808",
		time: "4 hours ago",
		comment: "45",
	},
	{
		title: "You need to know what right-half-plane zeros are 4",
		website: "jbconsulting.substack.com",
		points: "138",
		name: "jbay808",
		time: "4 hours ago",
		comment: "45",
	},
	{
		title: "You need to know what right-half-plane zeros are",
		website: "(jbconsulting.substack.com)",
		points: "138",
		name: "jbay808",
		time: "4 hours ago",
		comment: "45",
	},
	{
		title:
			"uBlacklist – Block specific sites from appearing in Google search results",
		website: "(github.com/iorate)",
		points: "26",
		name: "sanketpatrikar",
		time: "24 minutes ago",
		comment: "45",
	},
	{
		title: "You need to know what right-half-plane zeros are",
		website: "jbconsulting.substack.com",
		points: "138",
		name: "jbay808",
		time: "4 hours ago",
		comment: "45",
	},
	{
		title: "You need to know what right-half-plane zeros are",
		website: "jbconsulting.substack.com",
		points: "138",
		name: "jbay808",
		time: "4 hours ago",
		comment: "45",
	},
	{
		title: "You need to know what right-half-plane zeros are",
		website: "(jbconsulting.substack.com)",
		points: "138",
		name: "jbay808",
		time: "4 hours ago",
		comment: "45",
	},
	{
		title:
			"uBlacklist – Block specific sites from appearing in Google search results",
		website: "(github.com/iorate)",
		points: "26",
		name: "sanketpatrikar",
		time: "24 minutes ago",
		comment: "45",
	},
	{
		title: "You need to know what right-half-plane zeros are",
		website: "jbconsulting.substack.com",
		points: "138",
		name: "jbay808",
		time: "4 hours ago",
		comment: "45",
	},
	{
		title: "You need to know what right-half-plane zeros are",
		website: "jbconsulting.substack.com",
		points: "138",
		name: "jbay808",
		time: "4 hours ago",
		comment: "45",
	},
	{
		title: "You need to know what right-half-plane zeros are",
		website: "(jbconsulting.substack.com)",
		points: "138",
		name: "jbay808",
		time: "4 hours ago",
		comment: "45",
	},
	{
		title:
			"uBlacklist – Block specific sites from appearing in Google search results",
		website: "(github.com/iorate)",
		points: "26",
		name: "sanketpatrikar",
		time: "24 minutes ago",
		comment: "45",
	},
	{
		title: "You need to know what right-half-plane zeros are",
		website: "jbconsulting.substack.com",
		points: "138",
		name: "jbay808",
		time: "4 hours ago",
		comment: "45",
	},
	{
		title: "You need to know what right-half-plane zeros are",
		website: "jbconsulting.substack.com",
		points: "138",
		name: "jbay808",
		time: "4 hours ago",
		comment: "45",
	},
	{
		title: "You need to know what right-half-plane zeros are 4",
		website: "jbconsulting.substack.com",
		points: "138",
		name: "jbay808",
		time: "4 hours ago",
		comment: "45",
	},
	{
		title: "Our plans for Thunderbird on Android",
		website: "(jbconsulting.substack.com)",
		points: "138",
		name: "jbay808",
		time: "4 hours ago",
		comment: "45",
	},
	{
		title:
			"uBlacklist – Block specific sites from appearing in Google search results",
		website: "(github.com/iorate)",
		points: "26",
		name: "sanketpatrikar",
		time: "24 minutes ago",
		comment: "45",
	},
	{
		title: "Our plans for Thunderbird on Android",
		website: "jbconsulting.substack.com",
		points: "138",
		name: "jbay808",
		time: "4 hours ago",
		comment: "45",
	},
	{
		title: "Overthinking (2021)",
		website: "jbconsulting.substack.com",
		points: "138",
		name: "jbay808",
		time: "4 hours ago",
		comment: "45",
	},
	{
		title:
			"Thank HN: Five months ago, I was feeling like a loser, now I am opposite",
		website: "(jbconsulting.substack.com)",
		points: "138",
		name: "jbay808",
		time: "4 hours ago",
		comment: "45",
	},
	{
		title: "When Good Codenames Go Bad (2006)",
		website: "(github.com/iorate)",
		points: "26",
		name: "sanketpatrikar",
		time: "24 minutes ago",
		comment: "45",
	},
	{
		title: "You need to know what right-half-plane zeros are",
		website: "jbconsulting.substack.com",
		points: "138",
		name: "jbay808",
		time: "4 hours ago",
		comment: "45",
	},
	{
		title:
			"Amazon calls cops, fires workers in attempts to stop unionization nationwide",
		website: "jbconsulting.substack.com",
		points: "138",
		name: "jbay808",
		time: "4 hours ago",
		comment: "45",
	},
	{
		title: "System Preferences Reimagined on macOS",
		website: "(jbconsulting.substack.com)",
		points: "138",
		name: "jbay808",
		time: "4 hours ago",
		comment: "45",
	},
	{
		title:
			"Thank HN: Five months ago, I was feeling like a loser, now I am opposite",
		website: "(github.com/iorate)",
		points: "26",
		name: "sanketpatrikar",
		time: "24 minutes ago",
		comment: "45",
	},
	{
		title: "Show HN: Tuc – When cut doesn’t cut it",
		website: "jbconsulting.substack.com",
		points: "138",
		name: "jbay808",
		time: "4 hours ago",
		comment: "45",
	},
	{
		title: "Stanford’s war on social life",
		website: "jbconsulting.substack.com",
		points: "138",
		name: "jbay808",
		time: "4 hours ago",
		comment: "45",
	},
];
export default newsData;
